import type { Order, OrderStats } from './types'

// Available products for the order form item selector
export const AVAILABLE_PRODUCTS = [
  { id: '1', name: 'Wireless Noise-Cancelling Headphones', price: 299.99 },
  { id: '2', name: 'Ergonomic Office Chair', price: 549.0 },
  { id: '3', name: 'Mechanical Keyboard Pro', price: 189.99 },
  { id: '4', name: 'Leather Messenger Bag', price: 129.99 },
  { id: '5', name: 'Standing Desk Converter', price: 349.0 },
  { id: '6', name: '4K Ultra-Wide Monitor', price: 899.0 },
  { id: '7', name: 'Bamboo Wireless Charger', price: 49.99 },
  { id: '8', name: 'Minimalist Walnut Desk', price: 799.0 },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-001',
    orderNumber: '#ORD-2024-001',
    status: 'NEW',
    paymentStatus: 'PENDING',
    fulfillmentStatus: 'UNFULFILLED',
    totalAmount: 349.98,
    createdAt: '2024-12-01T09:14:00Z',
    customer: {
      id: 'usr-1',
      name: 'Alice Johnson',
      email: 'alice@example.com',
      avatarUrl: 'https://placehold.co/36x36/6366f1/ffffff?text=AJ',
    },
    items: [
      {
        id: 'item-001-1',
        productId: '1',
        name: 'Wireless Noise-Cancelling Headphones',
        quantity: 1,
        unitPrice: 299.99,
      },
      {
        id: 'item-001-2',
        productId: '7',
        name: 'Bamboo Wireless Charger',
        quantity: 1,
        unitPrice: 49.99,
      },
    ],
  },
  {
    id: 'ord-002',
    orderNumber: '#ORD-2024-002',
    status: 'PAID',
    paymentStatus: 'PAID',
    fulfillmentStatus: 'UNFULFILLED',
    totalAmount: 899.0,
    createdAt: '2024-12-02T11:32:00Z',
    customer: {
      id: 'usr-2',
      name: 'Bob Martinez',
      email: 'bob.m@company.io',
      avatarUrl: null,
    },
    items: [
      {
        id: 'item-002-1',
        productId: '6',
        name: '4K Ultra-Wide Monitor',
        quantity: 1,
        unitPrice: 899.0,
      },
    ],
  },
  {
    id: 'ord-003',
    orderNumber: '#ORD-2024-003',
    status: 'FULFILLED',
    paymentStatus: 'PAID',
    fulfillmentStatus: 'FULFILLED',
    totalAmount: 189.99,
    createdAt: '2024-12-03T08:05:00Z',
    customer: {
      id: 'usr-3',
      name: 'Carol White',
      email: 'carol.white@mail.com',
      avatarUrl: 'https://placehold.co/36x36/10b981/ffffff?text=CW',
    },
    items: [
      {
        id: 'item-003-1',
        productId: '3',
        name: 'Mechanical Keyboard Pro',
        quantity: 1,
        unitPrice: 189.99,
      },
    ],
  },
  {
    id: 'ord-004',
    orderNumber: '#ORD-2024-004',
    status: 'CANCELLED',
    paymentStatus: 'REFUNDED',
    fulfillmentStatus: 'UNFULFILLED',
    totalAmount: 549.0,
    createdAt: '2024-12-04T14:21:00Z',
    customer: {
      id: 'usr-4',
      name: 'David Lee',
      email: 'david.lee@example.com',
      avatarUrl: null,
    },
    items: [
      {
        id: 'item-004-1',
        productId: '2',
        name: 'Ergonomic Office Chair',
        quantity: 1,
        unitPrice: 549.0,
      },
    ],
  },
  {
    id: 'ord-005',
    orderNumber: '#ORD-2024-005',
    status: 'PAID',
    paymentStatus: 'PAID',
    fulfillmentStatus: 'UNFULFILLED',
    totalAmount: 129.99,
    createdAt: '2024-12-05T16:45:00Z',
    customer: {
      id: 'usr-5',
      name: 'Eva Chen',
      email: 'eva.chen@startup.co',
      avatarUrl: 'https://placehold.co/36x36/f59e0b/ffffff?text=EC',
    },
    items: [
      {
        id: 'item-005-1',
        productId: '4',
        name: 'Leather Messenger Bag',
        quantity: 1,
        unitPrice: 129.99,
      },
    ],
  },
  {
    id: 'ord-006',
    orderNumber: '#ORD-2024-006',
    status: 'FULFILLED',
    paymentStatus: 'PAID',
    fulfillmentStatus: 'FULFILLED',
    totalAmount: 1248.98,
    createdAt: '2024-12-06T10:00:00Z',
    customer: {
      id: 'usr-6',
      name: 'Frank Wilson',
      email: 'f.wilson@corp.net',
      avatarUrl: null,
    },
    items: [
      {
        id: 'item-006-1',
        productId: '8',
        name: 'Minimalist Walnut Desk',
        quantity: 1,
        unitPrice: 799.0,
      },
      {
        id: 'item-006-2',
        productId: '7',
        name: 'Bamboo Wireless Charger',
        quantity: 1,
        unitPrice: 49.99,
      },
      {
        id: 'item-006-3',
        productId: '3',
        name: 'Mechanical Keyboard Pro',
        quantity: 2,
        unitPrice: 189.99,
      },
    ],
  },
  {
    id: 'ord-007',
    orderNumber: '#ORD-2024-007',
    status: 'NEW',
    paymentStatus: 'PENDING',
    fulfillmentStatus: 'UNFULFILLED',
    totalAmount: 79.98,
    createdAt: '2024-12-07T07:30:00Z',
    customer: {
      id: 'usr-7',
      name: 'Grace Kim',
      email: 'grace.kim@email.com',
      avatarUrl: 'https://placehold.co/36x36/ec4899/ffffff?text=GK',
    },
    items: [
      {
        id: 'item-007-1',
        productId: '7',
        name: 'Bamboo Wireless Charger',
        quantity: 1,
        unitPrice: 49.99,
      },
      {
        id: 'item-007-2',
        productId: '4',
        name: 'Leather Messenger Bag',
        quantity: 1,
        unitPrice: 29.99,
      },
    ],
  },
  {
    id: 'ord-008',
    orderNumber: '#ORD-2024-008',
    status: 'FULFILLED',
    paymentStatus: 'PAID',
    fulfillmentStatus: 'FULFILLED',
    totalAmount: 299.99,
    createdAt: '2024-12-08T13:17:00Z',
    customer: {
      id: 'usr-8',
      name: 'Henry Brown',
      email: 'henry.b@personal.com',
      avatarUrl: null,
    },
    items: [
      {
        id: 'item-008-1',
        productId: '1',
        name: 'Wireless Noise-Cancelling Headphones',
        quantity: 1,
        unitPrice: 299.99,
      },
    ],
  },
  {
    id: 'ord-009',
    orderNumber: '#ORD-2024-009',
    status: 'PAID',
    paymentStatus: 'PAID',
    fulfillmentStatus: 'UNFULFILLED',
    totalAmount: 459.0,
    createdAt: '2024-12-09T09:55:00Z',
    customer: {
      id: 'usr-9',
      name: 'Isabella Davis',
      email: 'isabella@demo.org',
      avatarUrl: 'https://placehold.co/36x36/8b5cf6/ffffff?text=ID',
    },
    items: [
      {
        id: 'item-009-1',
        productId: '5',
        name: 'Standing Desk Converter',
        quantity: 1,
        unitPrice: 349.0,
      },
      {
        id: 'item-009-2',
        productId: '7',
        name: 'Bamboo Wireless Charger',
        quantity: 2,
        unitPrice: 49.99,
      },
      {
        id: 'item-009-3',
        productId: '4',
        name: 'Leather Messenger Bag',
        quantity: 1,
        unitPrice: 10.02,
      },
    ],
  },
  {
    id: 'ord-010',
    orderNumber: '#ORD-2024-010',
    status: 'CANCELLED',
    paymentStatus: 'REFUNDED',
    fulfillmentStatus: 'UNFULFILLED',
    totalAmount: 189.99,
    createdAt: '2024-12-10T15:40:00Z',
    customer: {
      id: 'usr-10',
      name: 'James Taylor',
      email: 'j.taylor@bizmail.com',
      avatarUrl: null,
    },
    items: [
      {
        id: 'item-010-1',
        productId: '3',
        name: 'Mechanical Keyboard Pro',
        quantity: 1,
        unitPrice: 189.99,
      },
    ],
  },
  {
    id: 'ord-011',
    orderNumber: '#ORD-2024-011',
    status: 'NEW',
    paymentStatus: 'PENDING',
    fulfillmentStatus: 'UNFULFILLED',
    totalAmount: 648.99,
    createdAt: '2024-12-11T08:22:00Z',
    customer: {
      id: 'usr-11',
      name: 'Karen Anderson',
      email: 'karen.a@sample.com',
      avatarUrl: 'https://placehold.co/36x36/3b82f6/ffffff?text=KA',
    },
    items: [
      {
        id: 'item-011-1',
        productId: '5',
        name: 'Standing Desk Converter',
        quantity: 1,
        unitPrice: 349.0,
      },
      {
        id: 'item-011-2',
        productId: '1',
        name: 'Wireless Noise-Cancelling Headphones',
        quantity: 1,
        unitPrice: 299.99,
      },
    ],
  },
  {
    id: 'ord-012',
    orderNumber: '#ORD-2024-012',
    status: 'FULFILLED',
    paymentStatus: 'PAID',
    fulfillmentStatus: 'FULFILLED',
    totalAmount: 899.0,
    createdAt: '2024-12-12T12:00:00Z',
    customer: {
      id: 'usr-12',
      name: 'Liam Thompson',
      email: 'liam.t@webmail.com',
      avatarUrl: null,
    },
    items: [
      {
        id: 'item-012-1',
        productId: '6',
        name: '4K Ultra-Wide Monitor',
        quantity: 1,
        unitPrice: 899.0,
      },
    ],
  },
]

export const MOCK_ORDER_STATS: OrderStats = {
  total: MOCK_ORDERS.length,
  new: MOCK_ORDERS.filter((o) => o.status === 'NEW').length,
  paid: MOCK_ORDERS.filter((o) => o.status === 'PAID').length,
  fulfilled: MOCK_ORDERS.filter((o) => o.status === 'FULFILLED').length,
  cancelled: MOCK_ORDERS.filter((o) => o.status === 'CANCELLED').length,
}
